# Generated by Django 5.2 on 2025-05-06 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('msg', models.CharField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('group_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Delete', 'delete'), ('Modify', 'modify'), ('add', 'Add')], max_length=20, null=True)),
            ],
        ),
    ]
