# Generated by Django 5.2 on 2025-05-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='msg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Delete', 'delete'), ('Modify', 'modify'), ('Add', 'add')], max_length=20, null=True),
        ),
    ]
