# Generated by Django 5.2 on 2025-05-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_alter_event_date_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('delete', 'Delete'), ('modify', 'Modify'), ('add', 'Add')], max_length=20, null=True),
        ),
    ]
