# Generated by Django 5.2 on 2025-05-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_alter_event_date_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Delete', 'delete'), ('modify', 'Modify'), ('Add', 'add')], max_length=20, null=True),
        ),
    ]
