# Generated by Django 5.2 on 2025-04-18 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='grups_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='file',
            name='is_archieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='owner_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
