# Generated by Django 5.2 on 2025-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_grups_id_file_is_archieved_file_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='permits',
            field=models.IntegerField(default=777),
        ),
    ]
