# Generated by Django 5.2 on 2025-04-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_permits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='grups_id',
            new_name='group_id',
        ),
    ]
