# Generated by Django 5.2 on 2025-04-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_file_name_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='group_id',
            field=models.UUIDField(null=True),
        ),
    ]
