# Generated by Django 5.2 on 2025-04-28 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
