# Generated by Django 5.2 on 2025-05-27 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='eth_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
