# Generated by Django 5.2 on 2025-05-01 05:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(default='base'),
        ),
    ]
