# Generated by Django 5.2 on 2025-05-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
    ]
