# Generated by Django 5.2 on 2025-05-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_remove_group_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('base', 'Base'), ('Private', 'priv'), ('share', 'Share')], default='leader', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('Moderator', 'moderator'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
