# Generated by Django 5.2 on 2025-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_group_type_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('leader', 'Leader'), ('Moderator', 'moderator'), ('viewer', 'Viewer'), ('Private', 'priv')], default='viewer', max_length=20),
        ),
    ]
