# Generated by Django 5.2 on 2025-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_membership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
        migrations.AddField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('Leader', 'leader'), ('Moderator', 'moderator'), ('viewer', 'Viewer'), ('Private', 'priv')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Base', 'base'), ('Private', 'priv'), ('Share', 'share')], default='leader', max_length=20),
        ),
    ]
