# Generated by Django 5.2 on 2025-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_remove_membership_role_membership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Base', 'base'), ('priv', 'Private'), ('Share', 'share')], default='leader', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('Leader', 'leader'), ('Moderator', 'moderator'), ('Viewer', 'viewer'), ('priv', 'Private')], default='viewer', max_length=20),
        ),
    ]
