# Generated by Django 5.2 on 2025-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_group_type_alter_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('base', 'Base'), ('Private', 'priv'), ('share', 'Share')], default='leader', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('leader', 'Leader'), ('moderator', 'Moderator'), ('Viewer', 'viewer'), ('Private', 'priv')], default='viewer', max_length=20),
        ),
    ]
