# Generated by Django 5.2 on 2025-05-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_alter_group_type_alter_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('leader', 'Leader'), ('moderator', 'Moderator'), ('viewer', 'Viewer'), ('Private', 'priv')], default='viewer', max_length=20),
        ),
    ]
