# Generated by Django 5.2 on 2025-05-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_alter_group_type_alter_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('base', 'Base'), ('priv', 'Private'), ('share', 'Share')], default='leader', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='type',
            field=models.CharField(choices=[('Leader', 'leader'), ('Moderator', 'moderator'), ('Viewer', 'viewer'), ('priv', 'Private')], default='viewer', max_length=20),
        ),
    ]
