# Generated by Django 5.2 on 2025-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_alter_group_type_alter_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Base', 'base'), ('priv', 'Private'), ('Share', 'share')], default='leader', max_length=20),
        ),
    ]
