CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "client_client_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "client_id" bigint NOT NULL REFERENCES "client_client" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "client_client_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "client_id" bigint NOT NULL REFERENCES "client_client" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "client_client_groups_client_id_group_id_f5f6d81d_uniq" ON "client_client_groups" ("client_id", "group_id");
CREATE INDEX "client_client_groups_client_id_0a5113a5" ON "client_client_groups" ("client_id");
CREATE INDEX "client_client_groups_group_id_62427bf2" ON "client_client_groups" ("group_id");
CREATE UNIQUE INDEX "client_client_user_permissions_client_id_permission_id_56ef1ebf_uniq" ON "client_client_user_permissions" ("client_id", "permission_id");
CREATE INDEX "client_client_user_permissions_client_id_a5055ad6" ON "client_client_user_permissions" ("client_id");
CREATE INDEX "client_client_user_permissions_permission_id_133bea5f" ON "client_client_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "client_client" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "base_token" ("name" varchar NULL, "id" char(32) NOT NULL PRIMARY KEY, "exp_date" date NOT NULL, "client_id" bigint NOT NULL REFERENCES "client_client" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "base_token_client_id_8ab319b0" ON "base_token" ("client_id");
CREATE TABLE IF NOT EXISTS "client_client" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "phone_number" varchar(15) NULL, "file_groups" text NOT NULL CHECK ((JSON_VALID("file_groups") OR "file_groups" IS NULL)), "user_id" char(32) NOT NULL, "is_verified" bool NOT NULL, "verification_id" char(32) NOT NULL, "description" varchar NULL, "name" varchar NULL, "surname" varchar NULL, "address" varchar NULL, "avatar" varchar(200) NULL);
CREATE TABLE IF NOT EXISTS "groups_group" ("id" char(32) NOT NULL PRIMARY KEY, "name" varchar NULL, "creation_date" date NOT NULL, "description" varchar NULL, "type" varchar(20) NOT NULL);
CREATE TABLE IF NOT EXISTS "groups_membership" ("id" char(32) NOT NULL PRIMARY KEY, "group_id" char(32) NULL REFERENCES "groups_group" ("id") DEFERRABLE INITIALLY DEFERRED, "member_id" bigint NULL REFERENCES "client_client" ("id") DEFERRABLE INITIALLY DEFERRED, "type" varchar(20) NOT NULL);
CREATE INDEX "groups_membership_group_id_dcb8901e" ON "groups_membership" ("group_id");
CREATE INDEX "groups_membership_member_id_241678d9" ON "groups_membership" ("member_id");
CREATE TABLE IF NOT EXISTS "timeline_event" ("id" char(32) NOT NULL PRIMARY KEY, "msg" varchar(150) NULL, "group_id" char(32) NULL, "type" varchar(20) NULL, "date" datetime NOT NULL, "email" varchar(254) NULL);
