# Generated by Django 5.2 on 2025-04-24 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='verification_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
