# Generated by Django 5.2 on 2025-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_is_verified_client_verification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
