# Generated by Django 5.2 on 2025-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='skills',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, null=True),
        ),
    ]
