# Generated by Django 5.2 on 2025-04-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_name_client_skills_client_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='skills',
            new_name='address',
        ),
    ]
